### PR TITLE
Upgrade k8s client-go version to 9.0 (close #85)

### LINKED ISSUE #85: Upgrade client-go
This will support `credentials plugin` (useful for EKS authentication):

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

### PR DESCRIPTION
**Pull request by prateekpandey14**
1. Use `golang/dep` instead of `glide` as Go dependency management tool

2. Upgrade kubernets client-go version to latest 9.0 with required constraints as below in Gopkg.toml
```sh
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"
```
3.  Bump Go version 1.11 in Dockerfile for docker-build

4. Update vendor directory with latest kubernetes deps with respect to 9.0 client-go version.
fixes: #85

### CODE REVIEW

**Comment by prateekpandey14** [comment]
cc @tirumaraiselvan PTAL

**Comment by tirumaraiselvan** [comment]
@prateekpandey14 This is awesome. I ll take a look.

**Comment by tirumaraiselvan** [comment]
I have just updated the e2e tests: https://github.com/hasura/gitkube/pull/98

Once merged, we can test this one out.

**Comment by tirumaraiselvan** [comment]
@prateekpandey14 This is looking great. I just ran the tests and it worked. And it solves #85 for EKS.

**Comment by shark-h** [comment]
Whoa! :tada: :tada: :dancer:

GIF

Awesome work @prateekpandey14! :muscle: :trophy: All of us at Hasura :heart: what you did.

We would love to send you some swag! Please fill [this form](https://goo.gl/forms/4NxUyIeTVwyWjGqE3).

If you have any questions, ask us on our [Discord](https://discord.gg/3FNQnWj) & [Twitter](https://twitter.com/HasuraHQ)!

Thanks again :hugs:

**Comment by prateekpandey14** [comment]
Awesome @tirumaraiselvan  .... great to hear, it solves #85 .

**Pull request merged**
