### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by avirlrma**

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
Hi @avirlrma This reduces the visibility of the text IMO.

**Comment by avirlrma** [comment]
Hey! sorry for late reply. 
The brackets didn't look very professional, we can make it Italic/Bold if you like.

**Comment by avirlrma** [comment]
Hey! sorry for late reply. 
The brackets didn't look very professional, we can make it Italic/Bold if you like.

**Comment by avirlrma** [comment]
Hey! sorry for late reply. 
The brackets didn't look very professional, we can make it Italic/Bold if you like.

**Comment by avirlrma** [comment]
Hey! sorry for late reply. 
The brackets didn't look very professional, we can make it Italic/Bold if you like.

**Pull request closed without merging**
